### ISSUE TITLE
Produce a windows version

### ISSUE THREAD

**Issue by acartapanis** [Eneco/landscaper#103]
Is it possible to produce a windows version ? 
As there is a windows version for helm, it would be very useful.

**Comment by rollulus** [comment]
I guess it is possible, we can cross compile already for linux and mac. Feel free to do a PR since this appears as a rather niche to me.

**Comment by StianOvrevage** [comment]
I'm also looking for a Windows version. 3 of 6 people on my team use Windows for working with Kubernetes.

**Comment by rollulus** [comment]
PR is welcome. Say that I could build it for windows to begin with, I cannot even try it. Thanks.

**Comment by StianOvrevage** [comment]
I see the build process is using make so that makes it a bit more complicated. But I then realized that with Windows Subsystem for Linux (WSL) we can use the Linux binaries on Windows just fine 💃 

If anyone else comes here looking for a solution:

Install Win 10 and Ubuntu for Windows: https://tutorials.ubuntu.com/tutorial/tutorial-ubuntu-on-windows#0

Download and run Landscaper:

```
mkdir landscaper
cd landscaper
wget https://github.com/Eneco/landscaper/releases/download/v1.0.16/landscaper-1.0.16-linux-amd64.tar.gz
tar zxvf landscaper-1.0.16-linux-amd64.tar.gz
./landscaper version
```
