### ISSUE TITLE
Difference with helm upgrade

### ISSUE THREAD

**Issue by alebedev87** [Eneco/landscaper#27]
Hello!

I'm trying to understand the added value of `Landscaper` in comparison with simple `helm upgrade`.

Similar to `Lanscaper`, the upgrade can change a deployed release by applying the given values (`-f` or `--set`) to the given chart (chart reference or path to chart directory). And this can be added to your CI/CD chain to be triggered on merge.

So, what is the difference? and how do you see the combined usage of both of these solutions (if ever possible)?

Thank you,
Andrey

**Comment by rollulus** [comment]
Thanks for your question, and for being a bit critical. Landscaper is not a goal on itself, in our opinion it is convenient at the moment, but maybe it becomes obsolete if we find out that its job can be done in easier ways, so please ask difficult questions :).

Since landscaper is built on top of Helm, most or all it does can be done with a few `helm` commands. 

A few things that make it useful, in our opinion: 
 - Say that you want to get rid of a deployed release. With landscaper, you remove it from your desired state, and done. With a `helm` command in your CI/CD, how do you know that there is something out there? Sure, with a bit of shell magic you can figure that out, but this mimics the function of landscaper;
- Maybe a bit specific, but in k8s 1.4 and 1.5, it is impossible to upgrade a `CronJob` (aka `ScheduledJob`) due to bugs. We added logic in landscaper to delete/create instead. We found such a bit of centralized logic, in the form of landscaper, convenient;
 - Managing secrets. Currently, landscaper obtains them from the environment. There are plans for Vault support. 

Does this help?

**Comment by rollulus** [comment]
@alebedev87 feel free to re-open if it didn't help.

**Comment by alebedev87** [comment]
Thank you for your answer.
Yes, this helps. 
So, Landscaper can be considered as `kubectl apply` for Helm charts with additional features for secrets and CronJobs.
