### ISSUE TITLE
Release.Version?

### ISSUE THREAD

**Issue by philipbjorge** [Eneco/landscaper#66]
What is the release.version used for in a component definition?

```
release:
  version: 0.1.0
```

**Comment by rollulus** [comment]
It was meant to be a version of the component itself, and we used it in the early days to force redeployments by bumping it and thus artificially creating a diff. Since it has little use, and it confuses people (e.g. #58), I am planning to get rid of it, or at least make it optional. Does that help?

**Comment by philipbjorge** [comment]
That does help.

Are there any valid usecases for it today that you can think of?

**Comment by rollulus** [comment]
Not that I can think of.
